### ISSUE TITLE
Probably not a brotools issue but related

### ISSUE THREAD

**Issue by stepminer** [b-rodrigues/brotools#8]
Greetings Bruno,

Hope you are enjoying your vacation. Hope you can help with this soon. I have adapted your codes for clustering time series data with k-means to analyze Caribbean coronavirus data. The codes worked well the first time I used them, I want to redo the analysis with an extra 6 months of data to see if the clustering has changed.

I am getting the following error:

Error in do_one(nmeth) : NA/NaN/Inf in foreign function call (arg 1)
> wss
Error: object 'wss' not found

library(tidyverse)
library(lubridate)
library(brotools)
library(tidyquant)

 

corona_Can <-readr::read_csv("00_data/coronatsCarib.csv")
corona_Can1 <- corona_Can %>%
    
    
    select(Country, date, New_Cases_N)
corona_Can1

corona_wide <- corona_Can1 %>%
    pivot_wider(names_from = date, values_from = New_Cases_N)  %>%
    
    mutate_at(vars(-Country), as.numeric)
corona_wide
#thats the line which returns and error and does not calculate the wss
wss <- map_dbl(1:3, ~{kmeans(select(corona_wide, -Country), ., nstart=3,iter.max = 50 )$tot.withinss})
wss
Error in do_one(nmeth) : NA/NaN/Inf in foreign function call (arg 1)
> wss
Error: object 'wss' not found
n_clust <- 1:3
elbow_df <- as.data.frame(cbind("n_clust" = n_clust, "wss" = wss))
ggplot(elbow_df) +
    geom_line(aes(y = wss, x = n_clust), colour = "#82518c") +
    theme_tq() 

clusters <- kmeans(select(corona_wide, -Country), centers = 2)
(centers <- rownames_to_column(as.data.frame(clusters$centers), "cluster"))

corona_wide <- corona_wide %>% 
    mutate(cluster = clusters$cluster)

corona_long <- corona_wide %>%
    pivot_longer(cols=c(-Country, -cluster), names_to = "date", values_to = "New_Cases") 
corona_long  
centers_long <- centers %>%
    pivot_longer(cols = -cluster, names_to = "date", values_to = "New_Cases")   
centers_long

ggplot() +
    geom_point(data = corona_long, aes(y = New_Cases, x = date, group = Country), colour = "#82518c") +
    facet_wrap(~cluster, nrow = 1) + 
    geom_point(data = centers_long, aes(y = New_Cases, x = date, group = cluster), col = "#b58900", size = 1) +
    theme_tq() + 
    
    labs(title = "Coronavirus New Cases/Million population in 4 Caribbean countries", 
         caption = "The different time series have been clustered using k-means.
                 Cluster 1:Dominican_R  \nCluster 2:Haiti, Cuba, Jamaica ") +
    theme(plot.caption = element_text(colour = "black"))

**Comment by b-rodrigues** [comment]
looks like there's missing values in your Corona wide dataset, you might want to check for missings. you can use skimr::skim(corona_wide) or naniar::vis_miss(corona_wide) check out https://cran.r-project.org/web/packages/naniar/vignettes/getting-started-w-naniar.html

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by b-rodrigues** [comment]
fixed as per https://twitter.com/stepminer2/status/1424645756108124165?s=20
